version: '3.8'
services:
  demobox:
    build: .
    restart: "no" # Make this "unless-stopped" if you want to restart on failure
    volumes: # Change the sock and binary paths if they are different on your system
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./dockerfiles/default_dosh:/mnt/dockerfiles/default_dosh 
      - ./dockerfiles/custom_dosh:/mnt/dockerfiles/custom_dosh 
    ports:
      - "2002:22" 
    deploy:
      mode: replicated
      replicas: 1
