#!/bin/bash
/usr/bin/dockerc run \
--memory=256m \
--memory-swap=256m \
--kernel-memory=128m \
--cpus=0.3 \
--pids-limit=100 \
--no-healthcheck \
-it \
--rm \
--runtime="$(cat /etc/runtime)" \
demobox-child-$USER

