#!/bin/bash

# This script runs once when the master container is started up

# Stop the script on command error
set -e

echo set!

# Set the directory for the source of the child images
image_directory="/mnt/images/"

echo image!

# Install docker
#sudo apt install docker.io -y

# For each image in the image directory
#for image_path in $(find "$image_directory" -maxdepth 1  -type f); do
for image_path in /mnt/images/*.tar; do
    echo "for $image_path"
    # Load the image into docker
    sudo /usr/bin/dockerc load < "$image_path"
    echo loaded!
    # Get the name of the image for user creation
    name=$(echo "$image_path" | sed "s|^$image_directory||" | sed "s|^virtssh-children||" | sed "s|\.tar$||"  )
    echo "got $name"
    # LOG
    echo "Attempting to create user: $name"

    # Create a user with the name of the image (+set shell and create home)
    sudo useradd -m -s /bin/dosh $name 
    # Set the password of the user
    echo "$name:$name" | chpasswd
    # Add the user to the sudo group
    sudo adduser $name sudo

    # LOG
    echo "Created user: $name, from image: $image_path";

done


sudo /usr/sbin/sshd -D
