#!/bin/bash

# This script runs once when the master container is started up

# Stop the script on command error
set -e

source_directory="source"

for dir in $(find "$source_directory" -type d); do
    # Skip the root directory
    if [ "$dir" == "$source_directory" ]; then
        continue
    fi

    # Change into the child directory
    cd $dir

    # Construct the container name in the format: "childrenchild"
    name=$(echo "$dir" | tr -d '/' | sed "s|^$source_directory||")
    container_name="demobox-child-$name"

    # Build the child image
    /usr/bin/dockerc build -t $container_name .

    # LOG
    echo "Built child image $container_name from $dir successfully"

    # Return back to the root of the project
    cd -

    # LOG
    echo "Attempting to create user: $name"


    # Create a user with the name of the image (+set shell and create home)
    sudo useradd -m -s /bin/dosh $name 
    # Set the password of the user
    echo "$name:$name" | chpasswd
    # Add the user to the sudo group
    sudo adduser $name sudo

    # LOG
    echo "Created user: $name succesfully";


done

sudo /usr/sbin/sshd -D
